import { Inter, Montserrat, Laila, Work_Sans,Poiret_One, Didact_Gothic, Elsie} from 'next/font/google'
import './globals.css'
import { Providers } from '@/context/Providers'

const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

const laila = Laila({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

const poiretOne = Poiret_One({
    subsets: ['latin'],
  weight: ['400']

})

const elsie = Elsie({
  subsets: ['latin'],
  weight: ['400', '900']

})


const didactGothic = Didact_Gothic({
  subsets: ['latin'],
  weight: ['400']

})


export const metadata = {
  title: 'Priyada Arts',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.className} ${laila.className} ${workSans.className} ${poiretOne.className} ${didactGothic.className}  ${elsie.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
